// Generated by scripts/generate-test-catalog.mjs. Do not edit manually.
export type AdminTestCatalogEntry = {
  file: string;
  type: "unit" | "e2e";
  tests: string[];
};

export const adminTestCatalog: AdminTestCatalogEntry[] = [
  {
    "file": "tests/admin-notifications.test.ts",
    "type": "unit",
    "tests": [
      "audienceSchema accepts all 4 valid shapes",
      "audienceSchema rejects invalid shapes",
      "resolveAudience: single returns exactly the given user",
      "resolveAudience: plan resolves all matching user_settings rows",
      "resolveAudience: plan with no matches resolves to an empty recipient list",
      "resolveAudience: all resolves every listed auth user",
      "buildBroadcastRows: produces one row per recipient sharing the same batch_id",
      "buildBroadcastRows: empty recipient list produces no rows (broadcast with 0 recipients is rejected upstream)"
    ]
  },
  {
    "file": "tests/auth-redirect.test.ts",
    "type": "unit",
    "tests": [
      "safeInternalPath preserves valid in-app destinations",
      "safeInternalPath rejects external, protocol-relative and malformed destinations",
      "withNextParam safely carries checkout or invite intent through auth",
      "cookie consent parser only accepts explicit supported choices"
    ]
  },
  {
    "file": "tests/billing.test.ts",
    "type": "unit",
    "tests": [
      "buildCheckoutPlanKey only allows starter and pro paid combinations",
      "variant ids are resolved from server-side env only",
      "customer portal fallback requests a fresh Lemon customer URL",
      "lemon statuses are normalized to internal plan states",
      "plan expiry chooses the correct access window",
      "invalid webhook signatures are rejected and valid ones pass",
      "resolveLifecycleStatus: subscription_resumed/unpaused always become active regardless of raw status",
      "resolveLifecycleStatus: subscription_paused and subscription_expired are driven by the event name, not raw status",
      "resolveLifecycleStatus: subscription_cancelled treats a still-'active' raw status as cancelled when the cancelled flag is set",
      "resolveLifecycleStatus: subscription_updated passes through the raw status untouched (upgrade/downgrade keep their real status)",
      "resolveInvoiceDrivenStatus: a failed payment is always past_due even if the subscription still looks active",
      "resolveInvoiceDrivenStatus: a successful payment on a cancelled-but-still-active-looking subscription resolves to cancelled",
      "resolveInvoiceDrivenStatus: a successful payment on a healthy subscription resolves to active",
      "resolveCheckoutPlanKey: upgrading from starter to pro is detected from the new variant id, even with an existing plan key",
      "resolveCheckoutPlanKey: downgrading from pro to starter is detected the same way",
      "resolveCheckoutPlanKey: an explicit plan key from custom_data always wins over the variant id",
      "resolveCheckoutPlanKey: falls back to the existing plan key when the variant id can't be resolved"
    ]
  },
  {
    "file": "tests/blog-seo.test.ts",
    "type": "unit",
    "tests": [
      "blog slugs and titles are unique",
      "blog metadata stays within useful search snippet ranges",
      "every blog post has useful structure and internal links"
    ]
  },
  {
    "file": "tests/bulk-import-access.test.ts",
    "type": "unit",
    "tests": [
      "bulk organization imports require an active write-capable role",
      "bulk folders are restricted to their owner",
      "bulk styles allow own, system and public resources only"
    ]
  },
  {
    "file": "tests/bulk-import-api-db.test.ts",
    "type": "unit",
    "tests": [
      "bulk POST runs schema, authorization, database writes and replay end to end"
    ]
  },
  {
    "file": "tests/bulk-import-handler.test.ts",
    "type": "unit",
    "tests": [
      "bulk import history requires auth, clamps limits and disables caching",
      "bulk import history returns a safe database error",
      "bulk import handler rejects unauthenticated, invalid-key and invalid-body requests",
      "bulk import handler persists a ready batch and deterministic pending rows",
      "idempotency replay returns the original batch and rejects payload reuse",
      "plan access and monthly file limits are enforced before writes",
      "folder, organization and style boundaries return 403",
      "row insert failure deletes the incomplete batch and returns a safe error",
      "unique-key insert races resolve as an idempotent replay"
    ]
  },
  {
    "file": "tests/bulk-import-migration.test.ts",
    "type": "unit",
    "tests": [
      "bulk import migration applies and enforces RLS/claim invariants on PostgreSQL"
    ]
  },
  {
    "file": "tests/bulk-import.test.ts",
    "type": "unit",
    "tests": [
      "parseBulkCsv supports semicolon-delimited Turkish headers and quoted values",
      "parseBulkCsv rejects invalid URLs and skips duplicate normalized rows",
      "manual column mapping recovers files with unknown vendor headers",
      "parseBulkWorkbook reads the first XLSX sheet with the same mapping rules",
      "downloadable CSV and XLSX templates both parse into the same example rows",
      "createBulkImportSchema requires durable source row numbers",
      "bulk import slugs and payloads are deterministic across retries",
      "bulk creation modes match the capabilities promised by the UI",
      "only server-signed import dispatches can bypass the ordinary create rate limit",
      "retry progress only counts failed rows not yet attempted in the current retry run",
      "finished imports distinguish completed, partial and failed outcomes"
    ]
  },
  {
    "file": "tests/contact-upload.test.ts",
    "type": "unit",
    "tests": [
      "contact attachment names always use the verified MIME extension",
      "contact attachment MIME detection validates signatures and UTF-8 text",
      "contact request stream is assembled when it stays within the byte limit",
      "contact request stream aborts as soon as the byte ceiling is exceeded"
    ]
  },
  {
    "file": "tests/coupons.test.ts",
    "type": "unit",
    "tests": [
      "coupon codes are normalized for stable redemption",
      "generated coupon codes include a safe prefix",
      "date-only coupon validity resolves to end of day UTC"
    ]
  },
  {
    "file": "tests/custom-domains.test.ts",
    "type": "unit",
    "tests": [
      "isValidDomainFormat: accepts well-formed hostnames",
      "isValidDomainFormat: rejects malformed input",
      "generateVerificationToken: produces unique, sufficiently long tokens",
      "verificationRecordHost: prefixes the domain with the expected TXT record name",
      "verifyDomainTxtRecord: returns true when the TXT record contains the expected token",
      "verifyDomainTxtRecord: returns false when no record matches the token",
      "verifyDomainTxtRecord: returns false (not throws) when DNS lookup fails",
      "verifyDomainTxtRecord: joins multi-chunk TXT record parts before comparing",
      "provisionCustomDomainOnServer: runs the script directly via sudo -n (not via bash) so the sudoers rule on the script path matches",
      "provisionCustomDomainOnServer: surfaces stderr instead of throwing when the script fails (e.g. no sudo rights)",
      "provisionCustomDomainOnServer: never throws even on an unexpected error shape"
    ]
  },
  {
    "file": "tests/dashboard-navigation.test.ts",
    "type": "unit",
    "tests": [
      "dashboard navigation hides unused operational modules",
      "dashboard navigation follows the QR types the user actually owns"
    ]
  },
  {
    "file": "tests/delete-account.test.ts",
    "type": "unit",
    "tests": [
      "deleteUserAccount: blocks when the owner's organization has another active member",
      "deleteUserAccount: does not block when the other member is inactive (invited/rejected)",
      "deleteUserAccount: proceeds and deletes the auth user when there is no shared organization",
      "deleteUserAccount: surfaces an error result instead of throwing when auth deletion fails",
      "deleteUserAccount: a user with no organizations at all is never blocked"
    ]
  },
  {
    "file": "tests/e2e/bulk-upload.spec.ts",
    "type": "e2e",
    "tests": [
      "QR creation scene exposes and opens the bulk workflow",
      "CSV preview can be edited and submitted through the durable import API",
      "XLSX template previews on a mobile viewport without horizontal overflow",
      "failed history rows dispatch one retry run id"
    ]
  },
  {
    "file": "tests/e2e/exam-plan.spec.ts",
    "type": "e2e",
    "tests": [
      "public exam is keyboard reachable and responsive",
      "server plan badge and upgrade action have distinct accessible semantics",
      "expired server status cannot look active"
    ]
  },
  {
    "file": "tests/e2e/mvp-launch.spec.ts",
    "type": "e2e",
    "tests": [
      "landing exposes legal and pricing links",
      "signup page shows legal disclosure",
      "dashboard authenticated flow",
      "onboarding opens the QR builder as a visible modal",
      "public QR route resolves"
    ]
  },
  {
    "file": "tests/enterprise-checkout.test.ts",
    "type": "unit",
    "tests": [
      "enterprise checkout keys are recognized as checkout keys but excluded from the standard checkout",
      "enterprise variant ids resolve to enterprise checkout keys (both directions)",
      "webhook plan resolution: enterprise resolves from explicit plan_key and from the variant id",
      "resolveEnterpriseCheckoutPlanKey maps billing preference to the enterprise plan key",
      "applyEnterpriseLimits maps every purchased slider onto its enforcement field",
      "applyEnterpriseLimits returns the base tier untouched when there is no snapshot or values are invalid"
    ]
  },
  {
    "file": "tests/enterprise-pricing.test.ts",
    "type": "unit",
    "tests": [
      "default enterprise configuration produces the expected reference estimate",
      "enterprise pricing always uses integer cents",
      "invalid query values are normalized and clamped",
      "strict slider validation rejects out-of-range values",
      "search params can be rebuilt from enterprise state",
      "enterprise currency formatting stays in TRY"
    ]
  },
  {
    "file": "tests/enterprise-quote.test.ts",
    "type": "unit",
    "tests": [
      "quote request schema strips untrusted frontend price fields",
      "invalid email and invalid slider values are rejected",
      "contact normalization lowercases email and normalizes phone",
      "quote number generation is readable and stable",
      "rate limit rules reject excessive requests",
      "self-serve checkout flag and enterprise variant selection are resolved server-side",
      "selected checkout price is always recomputed from backend configuration"
    ]
  },
  {
    "file": "tests/exam-extra-time.test.ts",
    "type": "unit",
    "tests": [
      "exam deadline includes participant extra time",
      "unlimited exams do not receive a deadline",
      "latest audit event determines current extra time",
      "remaining time and expiry use server deadline with grace",
      "extra time is bounded to four hours"
    ]
  },
  {
    "file": "tests/exam.test.ts",
    "type": "unit",
    "tests": [
      "exam scoring happens from server-side correct answers",
      "public exam payload omits answer key and access secrets",
      "exam supports fill blank, multi select and manual essay scoring"
    ]
  },
  {
    "file": "tests/lemon-webhook.test.ts",
    "type": "unit",
    "tests": [
      "signature verification distinguishes missing secret, missing header and mismatch",
      "every handled event name maps to exactly one resource category",
      "subscription_created payload (data.type=subscriptions) validates against the subscription schema",
      "subscription_payment_success payload (data.type=subscription-invoices) is rejected by the subscription schema",
      "envelope schema accepts a realistic webhook body and exposes custom_data",
      "webhook user match falls back to exact normalized payment email",
      "malformed envelope (missing data.attributes) fails validation before any handler runs",
      "duplicate delivery of the same raw body produces the same idempotency hash"
    ]
  },
  {
    "file": "tests/organization-branding.test.ts",
    "type": "unit",
    "tests": [
      "resolveOrganizationBranding: uses brand_* overrides when set",
      "resolveOrganizationBranding: falls back to the organization's own name/logo when brand_* is unset",
      "resolveOrganizationBranding: returns null when the organization can't be found",
      "resolveQrBranding: returns null when the QR has no organization_id (no white-label applied)",
      "resolveQrBranding: resolves the owning organization's branding when organization_id is set"
    ]
  },
  {
    "file": "tests/organization-invites.test.ts",
    "type": "unit",
    "tests": [
      "organization invite tokens are fresh 256-bit hexadecimal values",
      "organization seat mutations for the same organization are serialized",
      "invite creation and acceptance both account for pending reservations and recheck after writes"
    ]
  },
  {
    "file": "tests/owner-notifications.test.ts",
    "type": "unit",
    "tests": [
      "buildOwnerNotificationContent: menu_order summary includes table, item count and amount",
      "buildOwnerNotificationContent: booking summary includes customer and time",
      "buildOwnerNotificationContent: feedback summary includes type and subject",
      "resolveOwnerEmail: prefers user_settings.notification_email override",
      "resolveOwnerEmail: falls back to Supabase Auth email when no override set",
      "resolveOwnerEmail: returns null when neither source has an email",
      "resolveOwnerWhatsAppNumber: returns the activated number",
      "resolveOwnerWhatsAppNumber: returns null when not activated",
      "resolveOwnerPhone: returns the saved phone number",
      "resolveOwnerPhone: returns null when profile has no phone",
      "notifyOwnerOfSubmission: calls the send function with the resolved email and built content",
      "notifyOwnerOfSubmission: skips sending and returns no_email when owner has no resolvable address",
      "notifyOwnerOfSubmission: swallows send errors and reports reason 'error' instead of throwing",
      "notifyOwnerOfSubmission: dispatches WhatsApp independently when the owner activated a number",
      "notifyOwnerOfSubmission: swallows WhatsApp send errors without affecting the email result",
      "notifyOwnerOfSubmission: dispatches SMS independently when the owner has a phone number",
      "notifyOwnerOfSubmission: swallows SMS send errors without affecting other channels"
    ]
  },
  {
    "file": "tests/plan-ui.test.ts",
    "type": "unit",
    "tests": [
      "known and custom plan labels have stable fallbacks",
      "active and unhealthy subscription states are never ambiguous",
      "all promised plan families have explicit contrast tokens"
    ]
  },
  {
    "file": "tests/plan-usage-migration.test.ts",
    "type": "unit",
    "tests": [
      "monthly bulk usage reservations are atomic and service-role only"
    ]
  },
  {
    "file": "tests/pricing-consistency.test.ts",
    "type": "unit",
    "tests": [
      "advertised QR capacities match enforced plan limits",
      "advertised team capacities match enforced plan limits"
    ]
  },
  {
    "file": "tests/qr-capabilities.test.ts",
    "type": "unit",
    "tests": [
      "static-only QR types never offer managed redirect mode",
      "hosted QR types require dynamic mode",
      "simple URL QR types support both modes",
      "explicit qr_mode has priority over legacy fields",
      "legacy records use is_dynamic and static payload fallbacks",
      "legacy capability fallback is safe and deterministic",
      "managed dynamic QR redirects always remain updateable"
    ]
  },
  {
    "file": "tests/qr-grouping.test.ts",
    "type": "unit",
    "tests": [
      "UTM campaigns group by trimmed reporting value",
      "folder membership does not change UTM campaign membership",
      "blank campaign values stay visible in an untagged reporting group"
    ]
  },
  {
    "file": "tests/qr-password-gate.test.ts",
    "type": "unit",
    "tests": [
      "unlockCookieName: stable for the same slug regardless of case",
      "unlockCookieName: different slugs produce different cookie names",
      "buildUnlockCookie + isUnlockCookieValid: round-trips for the correct slug/password pair",
      "isUnlockCookieValid: rejects when the password doesn't match",
      "isUnlockCookieValid: rejects a cookie issued for a different slug",
      "isUnlockCookieValid: rejects missing or malformed cookie values",
      "isUnlockCookieValid: rejects an expired cookie",
      "isUnlockCookieValid: rejects a tampered signature"
    ]
  },
  {
    "file": "tests/qr-templates.test.ts",
    "type": "unit",
    "tests": [
      "resolveQrTemplateId: template_id takes priority over style_id",
      "resolveQrDesignOverride: templates stay live until the QR is customized",
      "hasQrTemplateSelection: detects explicit template/style fields",
      "canUseQrTemplate: allows own, system and public templates only",
      "toApiQrTemplate: hides user_id and returns stable API shape"
    ]
  },
  {
    "file": "tests/rate-limit.test.ts",
    "type": "unit",
    "tests": [
      "checkRateLimit: allows requests up to the configured max, then blocks",
      "checkRateLimit: different keys have independent counters",
      "checkRateLimit: resets the window once it elapses",
      "clientIp: reads the first IP from x-forwarded-for",
      "clientIp: falls back to 'unknown' when header is missing",
      "tooManyRequestsResponse: returns 429 with Retry-After header",
      "RATE_LIMITS: every public-write limit has a positive max and window"
    ]
  },
  {
    "file": "tests/resolve-domain-owner.test.ts",
    "type": "unit",
    "tests": [
      "resolveVerifiedDomainOwnerId: returns null when host is missing",
      "resolveVerifiedDomainOwnerId: returns null for the main app domain (not a registered custom domain)",
      "resolveVerifiedDomainOwnerId: returns the owner's user_id for a verified custom domain",
      "resolveVerifiedDomainOwnerId: strips the port from the Host header before matching",
      "resolveVerifiedDomainOwnerId: returns null for a domain that exists but isn't verified yet (still pending)",
      "resolveVerifiedDomainOwnerId: matching is case-insensitive on the hostname"
    ]
  },
  {
    "file": "tests/schema-compat.test.ts",
    "type": "unit",
    "tests": [
      "schema compatibility detection accepts concrete Postgres/PostgREST schema errors",
      "schema compatibility detection does not classify ordinary text as a schema error",
      "database errors return the route fallback without exposing migration instructions",
      "schema compatibility detection only accepts concrete database errors",
      "database details remain in logs while users receive the route fallback"
    ]
  },
  {
    "file": "tests/seo-audit.test.ts",
    "type": "unit",
    "tests": [
      "private, loopback, metadata and documentation IP ranges are blocked",
      "URL validation only accepts standard public HTTP and HTTPS targets",
      "DNS resolution rejects private and mixed rebinding answers",
      "redirect targets are revalidated before a second request",
      "oversized and non-HTML responses are rejected",
      "HTML analysis returns sanitized fields and actionable checks"
    ]
  },
  {
    "file": "tests/slug.test.ts",
    "type": "unit",
    "tests": [
      "normalizeSlug transliterates Turkish dotted I and other Turkish letters",
      "normalizeSlug keeps underscores only when requested"
    ]
  },
  {
    "file": "tests/sms.test.ts",
    "type": "unit",
    "tests": [
      "isSmsConfigured: false when no provider env vars are set",
      "sendSms: returns disabled without calling fetch when unconfigured",
      "sendSms: Infobip path posts to the account base URL with App auth header",
      "sendSms: Infobip path throws with response body text on non-OK response",
      "sendSms: Iletimerkezi path posts key/hash auth and normalized TR phone number",
      "sendSms: Iletimerkezi path throws with API status message on non-success code",
      "sendSms: Twilio takes priority over Infobip when both are configured"
    ]
  },
  {
    "file": "tests/technical-seo.test.ts",
    "type": "unit",
    "tests": [
      "private, transactional and generated-output routes are noindex",
      "robots mirrors the central noindex route policy",
      "sitemap contains unique canonical URLs and excludes noindex routes",
      "metadata emits canonical and reciprocal homepage hreflang URLs",
      "JSON-LD uses canonical organization identity and escapes script breakers",
      "next response headers enforce noindex on non-HTML and output routes"
    ]
  },
  {
    "file": "tests/webhook-dispatch.test.ts",
    "type": "unit",
    "tests": [
      "dispatchWebhook: returns null without calling fetch when webhook_url is empty",
      "dispatchWebhook: sends a correctly HMAC-signed payload that the recipient can verify",
      "dispatchWebhook: omits the signature header when no secret is configured",
      "dispatchWebhook: retries once on failure before giving up",
      "dispatchWebhook: succeeds on the second attempt after a transient failure",
      "dispatchWebhook: never throws even when fetch always rejects (best-effort)",
      "buildWebhookPayload + signWebhookPayload: same payload and secret always produce the same signature"
    ]
  },
  {
    "file": "tests/whatsapp.test.ts",
    "type": "unit",
    "tests": [
      "isWhatsAppConfigured: false when either env var is missing",
      "isWhatsAppConfigured: true when both env vars are set",
      "sendWhatsAppMessage: skips the network call entirely when not configured",
      "sendWhatsAppMessage: posts a normalized phone number and text body to the Graph API",
      "sendWhatsAppMessage: rejects an empty/invalid phone number without calling fetch",
      "sendWhatsAppMessage: surfaces a Graph API error response instead of throwing",
      "sendWhatsAppMessage: never throws even when fetch rejects (best-effort)"
    ]
  }
];
