import type { FeedbackKind } from "@/lib/feedback";
import type { MenuOrder } from "@/lib/menu";
import type { PublicLocale } from "@/lib/public-locale";

export function publicLocaleTag(locale: PublicLocale) {
  return locale === "tr" ? "tr-TR" : "en-US";
}

export function formatPublicDate(value: string, locale: PublicLocale) {
  return new Date(`${value}T00:00:00`).toLocaleDateString(publicLocaleTag(locale), {
    weekday: "long",
    day: "2-digit",
    month: "long",
  });
}

export function formatPublicDateTime(value: string, locale: PublicLocale) {
  return new Intl.DateTimeFormat(publicLocaleTag(locale), {
    hour: "2-digit",
    minute: "2-digit",
    day: "2-digit",
    month: "2-digit",
  }).format(new Date(value));
}

export const menuStatusLabels: Record<PublicLocale, Record<MenuOrder["status"], string>> = {
  tr: {
    new: "Sipariş alındı",
    preparing: "Hazırlanıyor",
    done: "Tamamlandı",
    cancelled: "İptal edildi",
  },
  en: {
    new: "Order received",
    preparing: "Preparing",
    done: "Completed",
    cancelled: "Cancelled",
  },
};

export const menuCopy = {
  tr: {
    addToCart: "Sepete Ekle",
    protein: "Protein",
    carbs: "Karbonhidrat",
    fat: "Yağ",
    allergens: "Alerjen",
    discountFallback: "İndirim",
    cart: "Sepet",
    activeOrders: "aktif sipariş",
    tableRequired: "Masa QR gerekli",
    itemCount: "ürün",
    orderPanelTitle: "Masa Siparişi",
    orderPanelSubtle: "Mali değeri yoktur.",
    close: "Kapat",
    myOrders: "Siparişlerim",
    refresh: "Yenile",
    addNote: "Not ekle",
    noTable: "Masa yok",
    generalMenuWarning: "Bu link genel menü linki. Sipariş almak için panelden masaya özel QR çıktısı alın.",
    emptyCart: "Sepet boş.",
    submitLoading: "Gönderiliyor...",
    submitAction: "Siparişi Gönder",
    tableInline: "Masa",
    receivedForTable: (tableNo: number) => `Sipariş alındı. Masa ${tableNo}`,
    fetchOrdersError: "Sipariş durumu alınamadı.",
    submitError: "Sipariş gönderilemedi.",
    scanTableQr: "Sipariş vermek için masadaki QR kodu okutun.",
  },
  en: {
    addToCart: "Add to cart",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    allergens: "Allergens",
    discountFallback: "Discount",
    cart: "Cart",
    activeOrders: "active orders",
    tableRequired: "Table QR required",
    itemCount: "items",
    orderPanelTitle: "Table order",
    orderPanelSubtle: "For operational use only.",
    close: "Close",
    myOrders: "My orders",
    refresh: "Refresh",
    addNote: "Add note",
    noTable: "No table",
    generalMenuWarning: "This is a generic menu link. Use a table-specific QR from the dashboard to collect orders.",
    emptyCart: "Your cart is empty.",
    submitLoading: "Sending...",
    submitAction: "Send order",
    tableInline: "Table",
    receivedForTable: (tableNo: number) => `Order received. Table ${tableNo}`,
    fetchOrdersError: "Order status could not be loaded.",
    submitError: "Order could not be sent.",
    scanTableQr: "Scan the table QR code to place an order.",
  },
} as const;

export const bookingCopy = {
  tr: {
    missingTitle: "Rezervasyon bulunamadı",
    missingBody: "Bu randevu QR'ı aktif değil veya kaldırılmış.",
    unconfiguredTitle: "Bu QR henüz yapılandırılmamış",
    unconfiguredBody: "Rezervasyon takvimi ve saat aralığı tanımlandıktan sonra bu sayfa otomatik olarak aktifleştir.",
    defaultServiceType: "Rezervasyon",
    locationFallback: "Lokasyon belirtilmedi",
    dateLabel: "Tarih",
    timeLabel: "Saat",
    dateMissing: "Tarih aralığı tanımlanmamış.",
    fullName: "Ad soyad",
    email: "E-posta",
    phone: "Telefon",
    note: "Not (opsiyonel)",
    sendRequest: "Rezervasyon Talebi Gönder",
    sending: "Gönderiliyor...",
    inactiveTitle: "Rezervasyon kapalı",
    inactiveBody: "Bu QR için randevu alımı şu anda aktif değil.",
    pickDateTime: "Lütfen tarih ve saat seçin.",
    fullNameRequired: "Ad soyad zorunlu.",
    contactRequired: "E-posta veya telefon girin.",
    submitError: "Rezervasyon alınamadı.",
    capacity: "Kontenjan",
    minuteShort: "dk",
  },
  en: {
    missingTitle: "Booking not found",
    missingBody: "This booking QR is inactive or has been removed.",
    unconfiguredTitle: "This QR is not configured yet",
    unconfiguredBody: "This page will automatically go live once the booking calendar and time range are configured.",
    defaultServiceType: "Booking",
    locationFallback: "Location not specified",
    dateLabel: "Date",
    timeLabel: "Time",
    dateMissing: "No date range has been defined yet.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    note: "Note (optional)",
    sendRequest: "Send booking request",
    sending: "Sending...",
    inactiveTitle: "Booking closed",
    inactiveBody: "Reservations are currently disabled for this QR.",
    pickDateTime: "Please select a date and time.",
    fullNameRequired: "Full name is required.",
    contactRequired: "Enter an email or phone number.",
    submitError: "Booking request could not be submitted.",
    capacity: "Capacity",
    minuteShort: "min",
  },
} as const;

export const feedbackKindLabels: Record<PublicLocale, Record<FeedbackKind, string>> = {
  tr: {
    complaint: "Şikayet",
    suggestion: "Öneri",
    request: "İstek",
    thanks: "Teşekkür",
  },
  en: {
    complaint: "Complaint",
    suggestion: "Suggestion",
    request: "Request",
    thanks: "Thanks",
  },
};

export const feedbackCopy = {
  tr: {
    missingTitle: "Form bulunamadı",
    missingBody: "Bu geri bildirim formu aktif değil veya kaldırılmış.",
    unconfiguredTitle: "Bu QR henüz yapılandırılmamış",
    unconfiguredBody: "Form başlığı ve konu listesi tanımlandığında geri bildirim ekranı burada yayınlanır.",
    formClosedTitle: "Form şu anda kapalı",
    formClosedBody: "Bu QR lokasyonu için bildirim alımı geçici olarak durduruldu.",
    selection: "Seçim",
    qrLocation: "QR Lokasyonu",
    positiveFeedbackTitle: "Pozitif Geri Bildirim",
    feedbackType: "Bildirim Türü",
    tags: "Etiketler",
    subjectSelection: "Konu Seçimi",
    tapToSelect: "Dokunarak seçebilirsiniz",
    extraMessage: "Ek Açıklama",
    optional: "opsiyonel",
    messagePlaceholder: "Lütfen konuyu kişisel veri paylaşmadan kısa ve net anlatın...",
    contactInfo: "İletişim bilgisi",
    required: "zorunlu",
    optionalSentence: "opsiyonel",
    contactHelpRequired: "zorunlu. Sadece geri dönüş için kullanılır.",
    contactHelpOptional: "opsiyonel. Sadece geri dönüş için kullanılır.",
    fullName: "Ad soyad",
    email: "E-posta",
    phone: "Telefon",
    emailOrPhoneRequired: "E-posta veya telefon zorunlu",
    howItWorks: "Nasıl çalışır?",
    howItWorksBody: "Seçtiğiniz bildirim QR lokasyonuyla eşleşir ve ilgili panelde takip edilir.",
    selectionLimit: "Seçim limiti",
    privacy: "Gizlilik",
    privacyBody: "Kişisel veri paylaşmayın; bildirim yalnızca süreç takibi için kullanılır.",
    maxSelection: (count: number) => `En fazla ${count} seçim`,
    currentSelection: (count: number, max: number) => `${count} / ${max}`,
    pickSubjectError: "Lütfen en az bir konu seçin.",
    messageError: "Lütfen en az 5 karakterlik açıklama girin.",
    submitError: "Gönderilemedi.",
    successFallback: "Bildiriminiz alındı. Teşekkür ederiz.",
  },
  en: {
    missingTitle: "Form not found",
    missingBody: "This feedback form is inactive or has been removed.",
    unconfiguredTitle: "This QR is not configured yet",
    unconfiguredBody: "The feedback page will be published here once the form title and subject list are configured.",
    formClosedTitle: "Form is currently closed",
    formClosedBody: "Feedback collection is temporarily paused for this QR location.",
    selection: "Selection",
    qrLocation: "QR location",
    positiveFeedbackTitle: "Positive feedback",
    feedbackType: "Feedback type",
    tags: "Tags",
    subjectSelection: "Subject selection",
    tapToSelect: "Tap to select",
    extraMessage: "Additional message",
    optional: "optional",
    messagePlaceholder: "Please describe the issue briefly without sharing personal data...",
    contactInfo: "Contact info",
    required: "required",
    optionalSentence: "optional",
    contactHelpRequired: "required. It is only used for follow-up.",
    contactHelpOptional: "optional. It is only used for follow-up.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    emailOrPhoneRequired: "Email or phone is required",
    howItWorks: "How does it work?",
    howItWorksBody: "Your submission is matched with this QR location and tracked in the related dashboard.",
    selectionLimit: "Selection limit",
    privacy: "Privacy",
    privacyBody: "Do not share personal data; submissions are used only for process follow-up.",
    maxSelection: (count: number) => `Up to ${count} selections`,
    currentSelection: (count: number, max: number) => `${count} / ${max}`,
    pickSubjectError: "Please select at least one subject.",
    messageError: "Please enter at least 5 characters.",
    submitError: "Could not be submitted.",
    successFallback: "Your feedback has been received. Thank you.",
  },
} as const;
