import type { SeoLandingPageConfig } from "@/lib/seo-landing-pages";

export const seoUseCasePages: Record<string, SeoLandingPageConfig> = {
  restoranlar: {
    slug: "restoranlar",
    title: "Restoranlar İçin QR Kod | QR Menü ve Masa Akışı | QR Publish",
    description: "Restoranlar için QR menü, masa QR ve tarama raporlama akışlarını QR Publish ile tek panelden yönetin.",
    eyebrow: "Restoranlar İçin QR Kod",
    h1: "Restoran operasyonunuz için QR menü ve masa akışı kurun",
    intro: "QR Publish, restoranların dijital menü, masa QR ve tarama raporlama ihtiyaçlarını tek QR yönetim alanında toplamasına yardımcı olur.",
    benefits: ["Kategori ve ürün bilgileriyle QR menü", "Masa bazlı QR kullanımına uygun akış", "Menü ve QR performansını değerlendirme"],
    steps: ["Menü içeriğini oluşturun.", "Masa ve menü QR kodlarını yayınlayın.", "İçerik ve performansı panelden yönetin."],
    faqs: [{ question: "Restoran QR kodu nerede kullanılır?", answer: "Masa, vitrin, paket servis materyali ve menü erişimi gibi restoran temas noktalarında kullanılabilir." }, { question: "QR menü güncellenebilir mi?", answer: "Menü içeriğini panelden güncelleyerek QR menüyü güncel tutabilirsiniz." }, { question: "Masa QR desteği var mı?", answer: "Masa QR ve ilgili sipariş akışları restoran kullanım senaryoları için sunulur." }],
    relatedSlugs: ["restoran-qr-menu", "qr-kod-analiz", "dinamik-qr-kod-olusturucu"],
  },
  ajanslar: {
    slug: "ajanslar",
    title: "Ajanslar İçin QR Kod Yönetimi | QR Publish",
    description: "Ajans müşterileri için QR kod kampanyalarını, tasarımlarını, klasörlerini ve raporlamayı QR Publish ile yönetin.",
    eyebrow: "Ajanslar İçin QR Kod",
    h1: "Ajans müşterileriniz için QR kampanyalarını yönetin",
    intro: "Birden fazla kampanya ve müşteri çalışmasında QR kodları düzenli tutmak için klasör, tasarım, dinamik yönetim ve raporlama araçlarını birlikte kullanın.",
    benefits: ["Kampanya ve müşteri bazlı QR arşivi", "Markaya uygun QR tasarım yönetimi", "Tarama verileriyle kampanya değerlendirme"],
    steps: ["Kampanya QR kodlarını oluşturun.", "Klasör ve tasarım ayarlarını düzenleyin.", "Raporlarla performansı değerlendirin."],
    faqs: [{ question: "Ajanslar QR kodları müşteri bazında yönetebilir mi?", answer: "QR kodlarınızı klasör ve organizasyon yapısına uygun biçimde düzenleyebilirsiniz." }, { question: "Kampanya QR kodları sonradan güncellenebilir mi?", answer: "Dinamik QR akışlarında desteklenen hedef ve içerik ayarlarını yönetebilirsiniz." }, { question: "Ajans raporlama ihtiyacını karşılar mı?", answer: "Planınıza dahil QR ve klasör bazlı raporlama ile performans görünümü sağlayabilirsiniz." }],
    relatedSlugs: ["dinamik-qr-kod-olusturucu", "qr-kod-analiz", "toplu-qr-kod-olusturma"],
  },
  egitim: {
    slug: "egitim",
    title: "Eğitim İçin QR Kod Oluşturucu | QR Publish",
    description: "Eğitim materyali, duyuru ve dijital kaynaklara hızlı erişim için QR kod oluşturun ve yönetin.",
    eyebrow: "Eğitim İçin QR Kod",
    h1: "Eğitim materyallerini QR kodla erişilebilir hale getirin",
    intro: "Ders materyali, duyuru, kayıt formu veya dijital kaynak bağlantılarını QR kodla paylaşarak öğrenciler ve veliler için erişimi kolaylaştırın.",
    benefits: ["Dijital kaynağa hızlı erişim", "Basılı materyal ve sınıf içi kullanım", "İçerik bağlantılarını düzenli yönetme"],
    steps: ["Paylaşacağınız kaynağı hazırlayın.", "Kaynak bağlantısı için QR kod oluşturun.", "QR kodu sınıf veya materyallerde kullanın."],
    faqs: [{ question: "QR kod eğitimde nasıl kullanılır?", answer: "Ders materyali, video, doküman, form ve duyuru bağlantılarına erişim için kullanılabilir." }, { question: "Bir kaynak değişirse QR kod güncellenebilir mi?", answer: "Uygun dinamik QR senaryolarında hedef bağlantı yönetimi panelden yapılabilir." }, { question: "QR kodlar toplu hazırlanabilir mi?", answer: "Çok sayıda kaynak için toplu QR oluşturma akışından yararlanabilirsiniz." }],
    relatedSlugs: ["pdf-qr-kod-olusturucu", "toplu-qr-kod-olusturma", "qr-kod-olusturucu"],
  },
  etkinlikler: {
    slug: "etkinlikler",
    title: "Etkinlikler İçin QR Kod Oluşturucu | QR Publish",
    description: "Etkinlik kayıtları, program, ürün bilgisi ve iletişim akışları için QR kod oluşturun ve kampanya performansını takip edin.",
    eyebrow: "Etkinlikler İçin QR Kod",
    h1: "Etkinlik temas noktalarınızı QR kodla yönetin",
    intro: "Fuar, konferans, lansman ve organizasyonlarda program, kayıt, ürün veya iletişim bağlantılarını QR kodla paylaşarak katılımcı yolculuğunu sadeleştirin.",
    benefits: ["Etkinlik materyalinden dijital içeriğe geçiş", "Ürün ve iletişim QR akışları", "Tarama eğilimlerini izleme"],
    steps: ["Etkinlikte paylaşacağınız içerikleri belirleyin.", "Her temas noktası için QR kod oluşturun.", "Etkinlik sonrası performansı değerlendirin."],
    faqs: [{ question: "Etkinlik QR kodu ne için kullanılır?", answer: "Kayıt, program, ürün bilgisi, iletişim ve kampanya bağlantılarına hızlı erişim için kullanılır." }, { question: "Her stant veya ürün için ayrı QR kod oluşturabilir miyim?", answer: "Farklı içerik ve kampanyalar için ayrı QR kodlar oluşturup yönetebilirsiniz." }, { question: "Etkinlik QR performansı ölçülebilir mi?", answer: "Planınıza uygun raporlama ile tarama verilerini takip edebilirsiniz." }],
    relatedSlugs: ["qr-kod-analiz", "whatsapp-qr-kod-olusturucu", "toplu-qr-kod-olusturma"],
  },
  perakende: {
    slug: "perakende",
    title: "Perakende İçin QR Kod | QR Publish",
    description: "Perakende ürün bilgisi, kampanya, katalog ve müşteri iletişimi için QR kod oluşturun ve yönetin.",
    eyebrow: "Perakende İçin QR Kod",
    h1: "Perakende kampanya ve ürün bilgilerini QR kodla paylaşın",
    intro: "Ürün rafı, vitrin, katalog ve kampanya materyallerinde QR kod kullanarak müşterileri güncel bilgi ve dijital içeriklere yönlendirin.",
    benefits: ["Ürün ve kampanya bağlantılarına erişim", "Basılı materyalde güncellenebilir dijital akış", "QR performansını değerlendirme"],
    steps: ["Ürün veya kampanya içeriğini hazırlayın.", "QR kodu tasarlayıp yayınlayın.", "QR kodu satış alanlarında kullanın."],
    faqs: [{ question: "Perakendede QR kod nerede kullanılır?", answer: "Raf etiketi, vitrin, ambalaj, katalog ve kampanya materyallerinde kullanılabilir." }, { question: "Kampanya bağlantısı değişirse ne olur?", answer: "Dinamik QR senaryolarında desteklenen hedef ayarlarını panelden güncelleyebilirsiniz." }, { question: "QR kampanya sonuçları izlenebilir mi?", answer: "Planınıza dahil raporlama araçlarıyla tarama verilerini inceleyebilirsiniz." }],
    relatedSlugs: ["dinamik-qr-kod-olusturucu", "qr-kod-takip", "pdf-qr-kod-olusturucu"],
  },
  emlak: {
    slug: "emlak",
    title: "Emlak İçin QR Kod Oluşturucu | QR Publish",
    description: "İlan, portföy, doküman ve iletişim bağlantılarınızı emlak QR kodlarıyla paylaşın.",
    eyebrow: "Emlak İçin QR Kod",
    h1: "Emlak ilan ve portföylerinizi QR kodla paylaşın",
    intro: "İlan panosu, broşür, portföy ve kartvizitlerde QR kod kullanarak müşterileri ilan, doküman veya iletişim kanallarına hızlıca yönlendirin.",
    benefits: ["İlan ve portföy bağlantılarına hızlı erişim", "Broşür ve kartvizit kullanımına uygun QR", "İletişim ve doküman akışlarını birleştirme"],
    steps: ["İlan veya portföy bağlantınızı hazırlayın.", "İçeriğe uygun QR kodu oluşturun.", "QR kodu portföy ve tanıtım materyallerinde kullanın."],
    faqs: [{ question: "Emlak ilanı için QR kod nasıl kullanılır?", answer: "İlan sayfası, portföy, video veya iletişim bağlantısına yönlendiren QR kod oluşturabilirsiniz." }, { question: "Kartvizitte QR kod kullanabilir miyim?", answer: "Dijital kartvizit ve iletişim akışları için vCard QR kodu kullanabilirsiniz." }, { question: "İlan bağlantısı güncellenebilir mi?", answer: "Uygun dinamik QR senaryolarında hedef bağlantı panelden yönetilebilir." }],
    relatedSlugs: ["vcard-qr-kod-olusturucu", "pdf-qr-kod-olusturucu", "dinamik-qr-kod-olusturucu"],
  },
  pazarlama: {
    slug: "pazarlama",
    title: "Pazarlama İçin QR Kod | Kampanya QR Yönetimi | QR Publish",
    description: "Pazarlama kampanyaları için QR kod oluşturun, tasarlayın ve tarama performansını QR Publish ile takip edin.",
    eyebrow: "Pazarlama İçin QR Kod",
    h1: "Pazarlama kampanyalarınızı QR kodla ölçülebilir hale getirin",
    intro: "Basılı kampanya, ürün ambalajı, sosyal medya ve etkinlik temas noktalarında QR kod kullanarak kullanıcıları dijital içeriğe yönlendirin ve tarama performansını değerlendirin.",
    benefits: ["Kampanya hedeflerine QR yönlendirmesi", "Tasarım ve marka görünümü kontrolü", "Tarama verileriyle performans değerlendirme"],
    steps: ["Kampanya hedefini belirleyin.", "QR kodu tasarlayıp yayınlayın.", "Tarama verilerini analiz edin."],
    faqs: [{ question: "Kampanya QR kodu nedir?", answer: "Kampanya QR kodu, kullanıcıları kampanya hedefi olan dijital içeriğe yönlendiren QR koddur." }, { question: "QR kodla UTM kullanabilir miyim?", answer: "Kampanya bağlantınız UTM parametreleri içeriyorsa QR kod bu bağlantıyı paylaşabilir." }, { question: "Kampanya taramaları takip edilebilir mi?", answer: "Planınıza dahil raporlama ile QR tarama eğilimlerini inceleyebilirsiniz." }],
    relatedSlugs: ["qr-kod-analiz", "dinamik-qr-kod-olusturucu", "toplu-qr-kod-olusturma"],
  },
  urunler: {
    slug: "urunler",
    title: "Ürün Ambalajı İçin QR Kod | QR Publish",
    description: "Ürün ambalajı, katalog ve ürün bilgisi için QR kod oluşturun; müşterileri güncel dijital içeriğe yönlendirin.",
    eyebrow: "Ürünler İçin QR Kod",
    h1: "Ürün ambalajınızı QR kodla dijital içeriğe bağlayın",
    intro: "Ürün ambalajı ve kataloglarda QR kod kullanarak müşterileri ürün bilgisi, doküman, kampanya veya iletişim içeriğine yönlendirebilirsiniz.",
    benefits: ["Ambalajdan ürün bilgisine geçiş", "Katalog ve doküman paylaşımı", "Güncellenebilir hedef bağlantı akışı"],
    steps: ["Ürün içeriğini veya bağlantısını hazırlayın.", "QR kodu markanıza göre tasarlayın.", "QR kodu ambalaj ve katalogda kullanın."],
    faqs: [{ question: "Ürün ambalajında QR kod ne işe yarar?", answer: "Ürün bilgisi, kullanım kılavuzu, kampanya veya destek bağlantısına erişim sağlar." }, { question: "Ambalaj basıldıktan sonra bağlantı değişebilir mi?", answer: "Uygun dinamik QR senaryolarında hedef bağlantı yönetimi panelden yapılabilir." }, { question: "Ürün dokümanı için QR kod oluşturabilir miyim?", answer: "PDF veya paylaşılan doküman bağlantısı için QR kod oluşturabilirsiniz." }],
    relatedSlugs: ["pdf-qr-kod-olusturucu", "dinamik-qr-kod-olusturucu", "qr-kod-analiz"],
  },
};
